optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.0005,
    weight_decay: 0.1
  } }

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 200,
    initial_epochs: 20
  } }

dataset: {
  train: { _base_: cfgs/dataset_configs/Protein-EC.yaml,
           others: { subset: 'train' } },
  val: { _base_: cfgs/dataset_configs/Protein-EC.yaml,
         others: { subset: 'val' } },
  test: { _base_: cfgs/dataset_configs/Protein-EC.yaml,
          others: { subset: 'test' } } }
model: {
  NAME: PointMambaScan,
  trans_dim: 384,
  depth: 12,
  cls_dim: 7,
  num_heads: 6,
  group_size: 32,
  num_group: 32,
  encoder_dims: 384,
  rms_norm: False,
  drop_path: 0.5,
  drop_out: 0.1,
  use_cls_token: False,
  max_head: True,
  avg_head: False,
}


npoints: 512
total_bs: 128
step_per_update: 1
max_epoch: 200
grad_norm_clip: 10